// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABM5twsVYpSKcD_N11HOUr3zrKbNM2e4',
    appId: '1:224740141848:web:5fffb710d13f15cba54c6d',
    messagingSenderId: '224740141848',
    projectId: 'go-healthy-283-project-app',
    authDomain: 'go-healthy-283-project-app.firebaseapp.com',
    databaseURL: 'https://go-healthy-283-project-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'go-healthy-283-project-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3w2bFKTd5iw4rygASIfcMfgTUcG0-HAQ',
    appId: '1:224740141848:android:dfaae2ff81a09fe9a54c6d',
    messagingSenderId: '224740141848',
    projectId: 'go-healthy-283-project-app',
    databaseURL: 'https://go-healthy-283-project-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'go-healthy-283-project-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbbYqZlGngYBfUWdsdFDAGFajOSlV5vY4',
    appId: '1:224740141848:ios:fd4abc24086a3078a54c6d',
    messagingSenderId: '224740141848',
    projectId: 'go-healthy-283-project-app',
    databaseURL: 'https://go-healthy-283-project-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'go-healthy-283-project-app.appspot.com',
    iosBundleId: 'com.example.goHealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbbYqZlGngYBfUWdsdFDAGFajOSlV5vY4',
    appId: '1:224740141848:ios:fd4abc24086a3078a54c6d',
    messagingSenderId: '224740141848',
    projectId: 'go-healthy-283-project-app',
    databaseURL: 'https://go-healthy-283-project-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'go-healthy-283-project-app.appspot.com',
    iosBundleId: 'com.example.goHealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDABM5twsVYpSKcD_N11HOUr3zrKbNM2e4',
    appId: '1:224740141848:web:5b3e353c911030a3a54c6d',
    messagingSenderId: '224740141848',
    projectId: 'go-healthy-283-project-app',
    authDomain: 'go-healthy-283-project-app.firebaseapp.com',
    databaseURL: 'https://go-healthy-283-project-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'go-healthy-283-project-app.appspot.com',
  );
}
